/**
 * 字段映射配置
 * 定义原始数据字段到输出的转换规则
 */

// 船体映射
export const 船体 = {
    "名字": "(.index + .upgrade.hull)",
    "类型": ".group",
    "等级": ".level",
    "舰种": ".species",
    "国家": ".nation",
    "血量": ".health",
    "血量(技能)": ".health-perk",
    "血量(最大血池)": ".health-max",
    "鱼雷防护": ".flood",
    "船头血量": ".modelMaxHP.Bow",
    "炮塔装甲血量": ".modelMaxHP.Cas",
    "船身整体血量": ".modelMaxHP.Hull",
    "上层建筑血量": ".modelMaxHP.SS",
    "辅助舱间血量": ".modelMaxHP.SSC",
    "船尾血量": ".modelMaxHP.St",
    "引擎溅射防护口径": ".engineSplashArmor",
    "舵机溅射防护口径": ".sgSplashArmor",
    "弹药库溅射防护口径": ".ammoSplashArmor",
    "水面隐蔽": ".visibilityFactor",
    "水面隐蔽(最小)": ".visibilityFactor-min",
    "空中隐蔽": ".visibilityFactorByPlane",
    "空中隐蔽(最小)": ".visibilityFactorByPlane-min",
    "烟内开火隐蔽": ".visibilityCoefGKInSmoke",
    "最大航速": ".maxSpeed",
    "最大航速(最大)": ".maxSpeed-max",
    "转舵时间": ".rudderTime",
    "转向半径": ".turningRadius",
    "引擎出力": ".enginePower",
    "推重比": ".thrustWeightRatio",
    "质量": ".tonnage",
    "长度": ".length",
    "宽度": ".width",
    "高度": ".height",
    "核心高度": ".citHeight",
    "甲板高度": ".casHeight",
    "水下最大航速": ".maxBuoSpeed",
    "水平舵转舵时间": ".buoRudderTime",
    "上浮下潜速度": ".buoADSpeed",
    "电池容量": ".batteryCapacity",
    "电力恢复": ".batteryRegen",
    "稀有度": ".rarity",
    "特色-弹射起步": ".special.ejectionStart",
    "特色-重型船壳": ".special.heavyHullArmor",
    "特色-轻型船壳": ".special.lightHullArmor",
    "特色-特殊维修小组": ".special.AccessoriesMaintenance",
    "特色-起始血量": ".special.startHealth"
}

// 火炮映射
export const 火炮 = {
    "名字": "(.index + .upgrade.hull + (if .upgrade.art == null then null else (.upgrade.art | tostring) end))",
    "类型": ".group",
    "等级": ".level",
    "舰种": ".species",
    "国家": ".nation",
    "规格": ".number",
    "口径": ".barrelDiameter",
    "装填时间": ".shotDelay",
    "射程": ".maxDist",
    "最大射程": ".maxDist-max",
    "180度转炮时间": ".rotationSpeed",
    "前齐射角": ".horizSector[0]",
    "后齐射角": ".horizSector[1]",
    "HE标伤": ".HEalphaDamage",
    "HE每分钟标伤": ".HEalphaDamagePM",
    "HE单轮齐射最大伤害": ".HEalphaDamagePH",
    "HE穿深": ".HEalphaPiercing",
    "IFHE穿深": ".HEalphaPiercing-ifhe",
    "HE点燃几率": ".HEburnProb",
    "HE每分钟点火期望": ".HEburnProbPM",
    "AP标伤": ".APalphaDamage",
    "AP每分钟最大伤害": ".APalphaDamagePM",
    "AP单轮齐射最大伤害": ".APalphaDamagePH",
    "AP碾压厚度": ".APbulletNeverRicochetArmor",
    "AP最小跳弹角": ".APbulletRicochetAt[0]",
    "AP最大跳弹角": ".APbulletRicochetAt[1]",
    "AP引信长度": ".APbulletDetonator",
    "AP引信触发阈值": ".APbulletDetonatorThreshold",
    "半穿甲弹标伤": ".CSalphaDamage",
    "半穿甲弹每分钟最大伤害": ".CSalphaDamagePM",
    "半穿甲弹单轮齐射最大伤害": ".CSalphaDamagePH",
    "半穿甲弹穿深": ".CSalphaPiercing",
    "半穿甲弹最小跳弹角": ".CSbulletRicochetAt[0]",
    "半穿甲弹最大跳弹角": ".CSbulletRicochetAt[1]",
    "模块血量": ".modelMaxHP",
    "溅射防护口径": ".splashArmor",
    "Sigma系数": ".sigmaCount",
    "水平散布公式": ".maxDispFormula",
    "垂直散布系数": ".verticalDispCoeff"
}

// 副炮映射
export const 副炮 = {
    "名字": "(.index + .upgrade.hull)",
    "类型": ".group",
    "等级": ".level",
    "舰种": ".species",
    "国家": ".nation",
    "射程": ".maxDist",
    "总计每分钟最大伤害": ".sumAlphaDamagePM",
    "规格1": ".number[0]",
    "装填时间1": ".shotDelay[0]",
    "模块血量1": ".modelMaxHP[0]",
    "溅射防护口径1": ".splashArmor[0]",
    "水平散布公式1": ".maxDispFormula[0]",
    "标伤1": ".alphaDamage[0]",
    "穿深1": ".alphaPiercingHE[0]",
    "点火率1": ".burnProb[0]",
    "每分钟最大伤害1": ".alphaDamagePM[0]",
    "规格2": ".number[1]",
    "装填时间2": ".shotDelay[1]",
    "模块血量2": ".modelMaxHP[1]",
    "溅射防护口径2": ".splashArmor[1]",
    "水平散布公式2": ".maxDispFormula[1]",
    "标伤2": ".alphaDamage[1]",
    "穿深2": ".alphaPiercingHE[1]",
    "点火率2": ".burnProb[1]",
    "每分钟最大伤害2": ".alphaDamagePM[1]",
    "规格3": ".number[2]",
    "装填时间3": ".shotDelay[2]",
    "模块血量3": ".modelMaxHP[2]",
    "溅射防护口径3": ".splashArmor[2]",
    "水平散布公式3": ".maxDispFormula[2]",
    "标伤3": ".alphaDamage[2]",
    "穿深3": ".alphaPiercingHE[2]",
    "点火率3": ".burnProb[2]",
    "每分钟最大伤害3": ".alphaDamagePM[2]"
}

// 鱼雷映射
export const 鱼雷 = {
    "名字": "(.index + .upgrade.hull + .upgrade.torp)",
    "类型": ".group",
    "等级": ".level",
    "舰种": ".species",
    "国家": ".nation",
    "型号": ".number",
    "装填手": ".loaders",
    "装填时间": ".shotDelay",
    "模块血量": ".modelMaxHP",
    "溅射防护口径": ".splashArmor",
    "标伤": ".portDamage",
    "基本伤害": ".alphaDamage",
    "溅射伤害": ".damage",
    "漏水系数": ".uwCritical",
    "射程": ".maxDist",
    "速度": ".speed",
    "发现距离": ".visibilityFactor",
    "反应时间": ".reactionTime",
    "上浮距离": ".armingDist",
    "180度旋转时间": ".rotationSpeed",
    "最小散布角度": ".torpedoAngles[0]",
    "最大散布角度": ".torpedoAngles[1]",
    "可单发": ".special.useOneShot",
    "可替换": ".special.alternative",
    "潜艇鱼雷类型": ".special.subTorpedoType",
    "投放距离": ".special.dropTargetAtDistance",
    "最大垂直速度": ".special.maxVerticalSpeed",
    "伤害深度": ".special.dod",
    "可击中目标": ".special.ignoreClasses",
    "溅射装甲系数": ".special.splashArmorCoeff"
}

// 防空映射
export const 防空 = {
    "名字": "(.index + .upgrade.hull)",
    "类型": ".group",
    "等级": ".level",
    "舰种": ".species",
    "国家": ".nation",
    "近程面板秒伤": ".nearPortDamage",
    "近程伤害": ".nearAreaDamage",
    "近程命中率": ".nearHitChance",
    "近程射程": ".nearMaxDistance",
    "近程伤害间隔": ".nearAreaDamageFrequency",
    "中程面板秒伤": ".mediumPortDamage",
    "中程伤害": ".mediumAreaDamage",
    "中程命中率": ".mediumHitChance",
    "中程射程": ".mediumMaxDistance",
    "中程伤害间隔": ".mediumAreaDamageFrequency",
    "远程面板秒伤": ".farPortDamage",
    "远程伤害": ".farAreaDamage",
    "远程命中率": ".farHitChance",
    "远程射程": ".farMaxDistance",
    "远程伤害间隔": ".farAreaDamageFrequency",
    "爆炸生成距离": ".bubbleMaxDistance",
    "爆炸伤害": ".bubbleDamage",
    "爆炸半径": ".bubbleRadius",
    "爆炸产生激活延迟": ".maxBubbleActivationDelay",
    "爆炸持续时间": ".bubbleDuration",
    "爆炸总数": ".sumBubbleCount",
    "路径内爆炸数量": ".innerBubbleCount",
    "路径内爆炸产生间隔": ".innerBubbleSpawnTimeRange",
    "路径内判定角度": ".innerBubbleZone",
    "路径外爆炸数量": ".outerBubbleCount",
    "路径外爆炸产生间隔": ".outerBubbleSpawnTimeRange",
    "路径外单侧判定角度": ".halfOuterBubbleZone",
    "手动防空冷却时间": ".prioritySectorCooldown"
}

// 飞机映射
export const 飞机 = {
    "名字": "(.index + (.upgrade.air // \"\"))",
    "类型": ".group",
    "等级": ".level",
    "舰种": ".species",
    "国家": ".nation",
    "飞机类型": ".planeType",
    "中队飞机": ".numInSquadron",
    "波次飞机": ".numInAttack",
    "飞机载弹": ".numInPlane",
    "机库": ".maxHangar",
    "整备时间": ".restoreTime",
    "基础血量": ".maxHealth",
    "血量(生存期望)": ".maxHealth-expect",
    "巡航速度": ".cruiseSpeed",
    "最大速度": ".maxSpeed",
    "攻击冷却时间": ".attackCooldown",
    "水面隐蔽": ".visibility",
    "引擎冷却": ".boostTime",
    "引擎填充时间": ".boostReloadTime",
    "最大散布": ".maxSpread",
    "最大散布(标准)": ".maxSpread-std",
    "最大散布(常规)": ".maxSpread-gen",
    "最小散布": ".minSpread",
    "最小散布(标准)": ".minSpread-std",
    "最小散布(常规)": ".minSpread-gen",
    "最大散布内圈": ".innerMaxSpread",
    "最小散布内圈": ".innerMinSpread",
    "投弹方式": ".diveType",
    "中央投弹概率": ".innerBombsPercentage",
    "口径": ".diametr",
    "弹种": ".ammoType",
    "标伤": ".alphaDamage",
    "点火率": ".burnProb",
    "穿深": ".piercing",
    "跳弹角最小": ".ricochetAt[0]",
    "跳弹角最大": ".ricochetAt[1]",
    "漏水系数": ".uwCritical",
    "射程": ".maxDist",
    "速度": ".speed",
    "发现距离": ".visibilityFactor",
    "上浮时间": ".armingTime",
    "战斗机": ".callFighters",
    "维修": ".healForsage",
    "特色": ".special",
    "i18nkey": ".upgrade.air | [.]"
}

// 空袭映射
export const 空袭 = {
    "名字": ".index",
    "类型": ".group",
    "等级": ".level",
    "舰种": ".species",
    "国家": ".nation",
    "可用数量": ".chargesNum",
    "攻击飞机数": ".numInAttack",
    "巡航速度": ".cruiseSpeed",
    "飞机载弹": ".numInPlane",
    "标伤": ".alphaDamage",
    "穿深": ".piercing",
    "点火率": ".burnProb",
    "落弹时间": ".fallTime",
    "最小散布": ".minSpread",
    "中央炸弹比例": ".innerBombsPercentage",
    "中央最小散布": ".innerMinSpread",
    "最大距离": ".maxDist",
    "装填时间": ".reloadTime"
}

// 消耗品映射
export const 消耗品 = {
    "名字": ".index",
    "类型": ".group",
    "等级": ".level",
    "舰种": ".species",
    "国家": ".nation",
    "1号槽": ".AbilitySlot0",
    "2号槽": ".AbilitySlot1",
    "3号槽": ".AbilitySlot2",
    "4号槽": ".AbilitySlot3",
    "5号槽": ".AbilitySlot4",
    "主炮助推装填器CD时间": ".Uab-reloadTime",
    "防御用对空火力CD时间": ".Uadd-reloadTime",
    "伤害控制小组次数": ".Ucc-numConsumables",
    "伤害控制小组CD时间": ".Ucc-reloadTime",
    "伤害控制小组持续时间": ".Ucc-workTime",
    "战斗机次数": ".Uf-numConsumables",
    "战斗机CD时间": ".Uf-reloadTime",
    "侦察机次数": ".Us-numConsumables",
    "侦察机CD时间": ".Us-reloadTime",
    "引擎增压次数": ".Usb-numConsumables",
    "引擎增压CD时间": ".Usb-reloadTime",
    "发烟机次数": ".Usg-numConsumables",
    "发烟机CD时间": ".Usg-reloadTime",
    "发烟机半径": ".Usg-radius",
    "维修小组次数": ".Urc-numConsumables",
    "维修小组CD时间": ".Urc-reloadTime",
    "维修小组持续时间": ".Urc-workTime"
}

// 特色映射
export const 特色 = {
    "名字": ".index",
    "类型": ".group",
    "等级": ".level",
    "舰种": ".species",
    "国家": ".nation",
    "副炮手动模式": ".specials.atbaManualMode",
    "爆发模式": ".specials.burstMode",
    "狂暴模式": ".specials.rageMode",
    "肾上腺素": ".specials.adrenaline"
}

// 弹道穿深映射
export const 弹道穿深 = {
    "名字": "(.index + .upgrade.hull + (if .upgrade.art == null then null else (.upgrade.art | tostring) end))",
    "类型": ".group",
    "等级": ".level",
    "舰种": ".species",
    "国家": ".nation",
    "弹药类型": ".ammoType",
    "弹重": ".Pms",
    "口径": ".Pdia",
    "风阻": ".Pad",
    "初速": ".Psp",
    "硬度": ".Pk",
    "转正": ".Pcnma",
    "出膛穿深": ".penVertAt0",
    "10KM穿深": ".penVertAt10",
    "14KM穿深": ".penVertAt14",
    "18KM穿深": ".penVertAt18",
    "22KM穿深": ".penVertAt22",
    "10KM落弹时间": ".flyTimeAt10",
    "14KM落弹时间": ".flyTimeAt14",
    "18KM落弹时间": ".flyTimeAt18",
    "22KM落弹时间": ".flyTimeAt22",
    "10KM落弹角": ".impactAngleAt10",
    "14KM落弹角": ".impactAngleAt14",
    "18KM落弹角": ".impactAngleAt18",
    "22KM落弹角": ".impactAngleAt22"
}

// 反潜武器映射
export const 反潜武器 = {
    "名字": ".index",
    "类型": ".group",
    "等级": ".level",
    "舰种": ".species",
    "国家": ".nation",
    "空袭可用数量": ".asChargesNum",
    "空袭飞机数": ".asNumInAttack",
    "空袭载弹": ".asNumInPlane",
    "空袭标伤": ".asAlphaDamage",
    "空袭最大距离": ".asMaxDist",
    "空袭装填时间": ".asReloadTime",
    "深弹可用数量": ".dcChargesNum",
    "深弹炸弹数量": ".dcNumInAttack",
    "深弹标伤": ".dcAlphaDamage",
    "深弹装填时间": ".dcReloadTime"
}

// 声呐映射
export const 声呐 = {
    "类型": ".group",
    "等级": ".level",
    "舰种": ".species",
    "国籍": ".nation",
    "名称": ".index",
    "声波射程": ".waveDistance",
    "声波装填": ".waveReloadTime",
    "声波速度": ".waveSpeed",
    "声波宽度": ".waveWidth",
    "声波隐蔽": ".waveVisibility",
    "高亮区持续时间": ".sectorLifeTime",
    "高亮区双ping持续时间": ".sectorLifeTime2",
    "高亮区宽度": ".sectorWidth",
    "高亮区刷新时间": ".sectorAlertTime"
}

// 映射表导出
export const mappings = {
    "船体": 船体,
    "火炮": 火炮,
    "副炮": 副炮,
    "鱼雷": 鱼雷,
    "防空": 防空,
    "飞机": 飞机,
    "空袭": 空袭,
    "消耗品": 消耗品,
    "特色": 特色,
    "弹道穿深": 弹道穿深,
    "反潜武器": 反潜武器,
    "声呐": 声呐
}

/**
 * 获取映射配置
 * @param {string} category - 类别名称
 * @returns {Object|null} - 映射配置
 */
export function getMapping(category) {
    return mappings[category] || null
}
